image: docker:dind

stages:
  - build

build-server:
    stage: build
    script:
        - docker build -f dockerfile.server .

build-frontend:
    stage: build
    script:
        - docker build -f dockerfile .

