image: docker:dind

stages:
  - build-and-push
  - deploy-to-swarm

build-server:
    stage: build-and-push
    script:
        - docker build -f dockerfile.server . --tag=$DOCKER_REGISTRY/$DOCKER_USERSPACE/quest-backend
        - docker login -u $DOCKER_USER -p $DOCKER_PW $DOCKER_REGISTRY
        - docker push $DOCKER_REGISTRY/$DOCKER_USERSPACE/quest-backend

build-frontend:
    stage: build-and-push
    script:
        - docker build -f dockerfile . --tag=$DOCKER_REGISTRY/$DOCKER_USERSPACE/quest-server
        - docker login -u $DOCKER_USER -p $DOCKER_PW $DOCKER_REGISTRY
        - docker push $DOCKER_REGISTRY/$DOCKER_USERSPACE/quest-server

deploy:
    stage: deploy-to-swarm
    script:
        - docker login -u $DOCKER_USER -p $DOCKER_PW $DOCKER_REGISTRY