version: '3.5'

networks:
  external:
    external: true
  internal:
    external: true

services:
  app: 
    image: "$DOCKER_REGISTRY/$DOCKER_USERSPACE/quest-frontend"
    networks:
      - internal
      - external
    ports:
      - 3000:80
  
  backend:
    image: "$DOCKER_REGISTRY/$DOCKER_USERSPACE/quest-server"
    networks:
      - internal
      - external
    ports:
      - 3001:3001

  database:
      image: "postgres"
      networks:
        - internal
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=Quests